@ApisModuleLec3_HostAddress = http://localhost:5059

GET {{ApisModuleLec3_HostAddress}}/weatherforecast/
Accept: application/json

### Post a new Card:
POST {{ApisModuleLec3_HostAddress}}/api/cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjY2YTY4Nzc0ODM1MWZiMTc5OTNjMWUwNiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJlbGx2aXMyQGVtYWlsLmNvbSIsIklzQWRtaW4iOiJmYWxzZSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJuYmYiOjE3MjI0NTAxMzQsImV4cCI6MTcyMjUzNjUzNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.0TjZRrrkLLXWMgLcIh1LnB3dPkQ8I16bAnGddjaxMFI
Content-Type: application/json

{
  "title": "a wonderful new card",
  "subtitle": "a test value for this card",
  "description": "a test value for new card\na test value for new card\n",
  "phone": "012-3211234",
  "email": "qwe@gmail.com",
  "web": "www.bing.com",
  "image": {
    "url": "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
    "alt": "image of something"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": 8920435
  }
}


### Post another new Card:
POST {{ApisModuleLec3_HostAddress}}/api/cards
Content-Type: application/json

{
  "title": "Pizza Card",
  "subtitle": "a pizza card",
  "description": "a test value for new card\na test value for new card\n",
  "phone": "012-3211234",
  "email": "pizza@gmail.com",
  "web": "www.pizza.com",
  "image": {
    "url": "https://img.izismile.com/img/img13/20201030/640/you_have_never_seen_something_like_this_640_36.jpg",
    "alt": "image of something"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": 8920435
  }
}

### Get all the cards:
GET {{ApisModuleLec3_HostAddress}}/api/cards

### Get a specific card by id:
GET {{ApisModuleLec3_HostAddress}}/api/cards/66a65aff911ef68c782b80eb


### Register a new User:
POST {{ApisModuleLec3_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": {
    "first": "Ell",
    "last": "Vis"
  },
  "phone": "0512345567",
  "email": "ellvis2@email.com",
  "password": "Abc!123Abc",
  "image": {
    "url": "https://fastly.picsum.photos/id/975/200/300.jpg",
    "alt": "The alt"
  },
  "address": {
    "state": "IL",
    "country": "Israel",
    "city": "Arad",
    "street": "Shoham",
    "houseNumber": 5,
    "zip": 8920435
  },
  "isBusiness": true
}

### login a User:
POST {{ApisModuleLec3_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ellvis2@email.com",
  "password": "Abc!123Abc"
}