@Lec7Practice_HostAddress = http://localhost:5160


GET {{Lec7Practice_HostAddress}}/api/products/


### Add a product:
POST {{Lec7Practice_HostAddress}}/api/products/
Content-Type: application/json

{
  "id": "456", 
  "name": "Coca cola",
  "price": 6.9
}

### Add a product:
POST {{Lec7Practice_HostAddress}}/api/products/
Content-Type: application/json

{
  "id": "123", 
  "name": "Bamba",
  "price": 6.9
}



### Delete a product:
DELETE {{Lec7Practice_HostAddress}}/api/products/11679fe6-31c6-43a9-901c-6cd547036e6c


### Update a product with id = 123
PUT {{Lec7Practice_HostAddress}}/api/products/5bddf14f-d106-425b-8901-d38e75400bfb
Content-Type:application/json

{
  "id": "123",
  "Name": "Bisli",
  "price": 7.39
}



### GET the weather controller
GET {{Lec7Practice_HostAddress}}/WeatherForecast